### ISSUE TITLE
Broadcasting Fails on Android 9.0

### ISSUE THREAD

**Issue by kir12** [android/connectivity#110]
I am testing this app on Android 9.0 and upon hitting the Broadcast Switch I get the below error:

```
2019-06-11 18:50:19.661 28219-28219/com.example.android.bluetoothadvertisements E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.bluetoothadvertisements, PID: 28219
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

How would I go about resolving this problem?

**Comment by isaidamier** [comment]
Thanks for reporting this issue. Has it been resolved?
