### ISSUE TITLE
Crash on broadcast device switched

### ISSUE THREAD

**Issue by agustinsivoplas** [android/connectivity#113]
I am running Android Oreo 8.1 in google pixel.

> 02-27 10:28:50.460 10260-10260/com.example.android.bluetoothadvertisements E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                                              Process: com.example.android.bluetoothadvertisements, PID: 10260
>                                                                                              android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE)
>                                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
>                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:106)
>                                                                                                  at android.os.Looper.loop(Looper.java:164)
>                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6494)
>                                                                                                  at java.lang.reflect.Method.invoke(Native Method)
>                                                                                                  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by rajathegde** [comment]
Same issue after changing goForeground method also.please help me to resolve this issue
